### PR TITLE
Always use distinct when counting entries in KnpPager

### LINKED ISSUE #43: Paginator count is wrong when there are more than 1 components in an action
https://github.com/stephpy/timeline/blob/master/src/ResultBuilder/Pager/KnpPager.php#L42

should be

```
$this->pager = $this->paginator->paginate($target, $page, $limit, array('distinct' => true));

### PR DESCRIPTION
**Pull request by venimus**
fixes #43

### CODE REVIEW

**Comment by stephpy** [comment]
thanks

**Comment by venimus** [comment]
I didn't think of it earlier, but actually it would be good to have a way to change the option, because someone might not want to use distinct for performance reasons.

**Comment by stephpy** [comment]
Yep, but the paginator count would be wrong, imo it's a good thing to keep distinct.

For performances reasons, user can easily override pager class. :)

**Comment by venimus** [comment]
:+1: It was what actually I did to fix the issue, but this part also needs refactoring because I had to override using Compiler pass. Just setting my class in settings.yml does not work because of service dependancies.

**Pull request merged**
